### ISSUE TITLE
Flush logs to stdout

### ISSUE THREAD

**Issue by luebken** [giantswarm/giantswarm-firstapp-python#2]
A user noted:
> At first I was a bit confused, because 'swarm logs' didn't log any request information, when I opened application url in a browser. But then I found that logs were buffered inside Python interpreter and not flushed to stderr/stdout. To fix this 'http.server' needs to be started with '-u' flag, e.g. 'python -um http.server'. After that logs from http server can be viewed with 'swarm logs'. You might want to update the example.

**Comment by marians** [comment]
Does this refer to "helloworld" or to this repo? Here, we do `python server.py`. The claim is valid though and I will address it here.

**Comment by maxbrieiev** [comment]
That statement was about [helloworld](https://github.com/giantswarm/helloworld) repo. To be able to view logs with `swarm logs` args should be updated to `"args": ["sh", "-c", "echo \"Hello from Giant Swarm. \\o/\" > index.html && python -um http.server"]`

**Comment by marians** [comment]
@maxbrieiev Thanks for the clarification!
